name: Run Methodology

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:  ['3.10']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run - Classical Analysis
        run: python -u classical_analysis/model.py

      - name: Run - LLM Embedding
        run: python -u llm_analysis/llm_embedding.py

      - name: Run - LLM Classification
        run: python -u llm_analysis/llm_classification.py
